### ISSUE TITLE
Document installation via YAML anchors

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/nord-alacritty#13]
Like [documented in the Alacritty wiki][w] the configuration file can contain multiple color schemes by using [the great YAML _anchor and aliases_ feature][yaa]. This is way better than the currently documented installation method that replaces the whole color scheme that was defined before.
By using YAML anchors the user can simply switch between multiple themes without the need to copy & paste them every time but only changing the reference name of the `colors` field.

```yaml
schemes:
  nord: &nord
    primary:
      #...
    cursor:
      # ...
    normal:
      #...
    bright:
      #...
    dim:
      # ...

colors: *nord
```

[w]: https://github.com/alacritty/alacritty/wiki/Color-schemes#multiple-schemes
[yaa]: https://yaml.org/spec/1.2/spec.html#id2765878
