### ISSUE TITLE
Missing variables

### ISSUE THREAD

**Issue by jpcirrus** [arcticicestudio/nord-alacritty#20]
Alacritty 1.10.1 includes the following variables which are missing in Nord:

```yaml
colors:
  primary:
    bright_foreground:
  search:
    focused_match:
      foreground:
      background:
  line_indicator:
    foreground:
    background:
  hints:  # Pull request #17
    start:
      foreground:
      background:
    end:
      foreground:
      background:
```
